### ISSUE TITLE
Chain gets stuck if first submission fails

### ISSUE THREAD

**Issue by eezcjkr** [leapdao/leap-node#104]
Scenario:
- 3 validator slots
- 1 slot filled (but validator doesnt have any ether)
- fresh chain
- run machine gun

When it's time to submit period the validator tries but errors due to lack of funds for gas. However the prevPeriod is updated in the bridgeState (it assumes the submission was successful). On retries, the validator will try submitting with this prevPeriod and will get reverted every time because it does not exist yet.

**Comment by johannbarbie** [comment]
removed from any milestone and added question tag, as this needs more investigation.

**Comment by troggy** [comment]
too old, no reoccurrence for a long time. Feel free to reopen in case of reoccurrence (ideally with steps to reproduce)
