### ISSUE TITLE
Make leap-node buildable on ARM processors

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-node#111]
Currently it's not easy to build and run leap-node on ARM processors (like Raspberry Pi). This is due to wrtc native lib which doesn't exist for ARM and doesn't even support it and therefore very hard to build (cross compilation is needed). As we want to have as many nodes on the network as possible, being able to run it easily on cheap equipment such as Raspberry Pi will potentially help to grow the number of participants.

**Comment by pinkiebell** [comment]
https://github.com/leapdao/leap-node/blob/master/lotion/index.js#L15

There are two functions using peer-channel.

It is also later used to serve the genesis file. But I'm not familiar enough with the node, do we need to serve the genesis file? - Has something todo with the txHttpServer, do we need that? 🤔

**Comment by troggy** [comment]
closed via https://github.com/leapdao/leap-node/pull/141/commits/ccd306bbdecbd7e7f5810761b19e649745cf474d
