### ISSUE TITLE
set up HTTPS and WSS for JSON RPC on testnet nodes

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#114]
### Delivery
- change terraform config to to expose JSON RPC via HTTPS and WSS. One way to do it is to use nginx: #68. Other way is to setup CloudFront distribution. 
- disallow non-secure access to JSON RPC
- expose HTTPS JSON RPC on port 443 (similar to old `testnet-1.leapdao.org`)
- apply configuration to the testnet nodes bootstrapped by LeapDAO (`node1.testnet.leapdao.org`, `node2.testnet.leapdao.org` etc)

### Bounty setup

gardener: @troggy / 10%
worker: @johannbarbie  / 80%
reviewer: <free> / 10%

**Comment by johannbarbie** [comment]
Other way is to setup ~CloudFront distribution~ an AWS Loadbalancer.
