### ISSUE TITLE
eth_getBalance JSON RPC always returns 0x0

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-node#115]
Environment: testnet http://34.250.91.182:8645
Prerequisites:
 * Account with balance on plasma (E.g. 0x83B3525e17F9eAA92dAE3f9924cc333c94C7E98a on testnet)
Reproduction:
1. Send JSON RPC request to get balance for account from prerequisites ( `{"method":"eth_getBalance","params":["0x83B3525e17F9eAA92dAE3f9924cc333c94C7E98a"],"id":1,"jsonrpc":"2.0"}` )
<EXPECTED: Account balance is returned; ACTUAL: 0x0 is returned)>

**Comment by troggy** [comment]
doesn't reproduce with updated testnet

**Comment by troggy** [comment]
Reproduced and resolved in https://github.com/leapdao/leap-node/issues/115
