### ISSUE TITLE
Problem with setting up local dev env

### ISSUE THREAD

**Issue by cryptonian-base** [leapdao/leap-node#121]
I've been setting up local development environment on my Mac.
Following this wiki (https://github.com/leapdao/leap-contracts/wiki/Setting-up-local-development-environment) has been helpful even though it seems outdated.

when I run "node index.js --config=../leap-contracts/build/nodeFiles/generatedConfig.json" 
the below error occurs.

unhandledRejection
Error: Invalid JSON RPC response: ""

I found out where this error happens. In "fetchEvents() at ContractEventsSubscription.js",
"getPastEvents from contract" might be the one.

I'd deployed leap_contracts with truffle running on my local Mac. 
When connecting to http://node1.testnet.leapdao.org:8645, It works fine.
Therefore, the local truffle must be the one which has some issues.
(On the truffle console, (bridge,operator,exit) contracts return [] when 'getPastEvents' is called with them.)

Any Idea of why this error is occuring? Thanks in advance.

**Comment by johannbarbie** [comment]
@cryptonian-base thanks for reporting. will try to reproduce.

**Comment by troggy** [comment]
https://github.com/leapdao/leap-contracts/wiki/Setting-up-local-development-environment has been updated to (almost) reflect the reality. Closing
