### ISSUE TITLE
setup testnet network nodes

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#122]
`> 3` node, so that if one crashes, 67% majority votes still passing.

**Comment by troggy** [comment]
Set up 3 validating nodes:

http://node1.testnet.leapdao.org
http://node2.testnet.leapdao.org
http://node3.testnet.leapdao.org

Running leap-node 3.1.0 with [leap-testnet-gamma config](https://github.com/leapdao/leap-node/blob/master/presets/leap-testnet-gamma.json)

**Comment by troggy** [comment]
failing with consensus errors

**Comment by troggy** [comment]
running just one node for a while
