### ISSUE TITLE
set up network monitoring

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#123]
## Scope
- check that periods are being submitted (there was a successful submission in the last 30 minutes). Report to Slack if not.
- check that PoA operators have enough ETH to submit periods. Report to Slack if the balance is less then Ξ0.01 (should be enough for submitting 16 periods for 8 gwei per gas)
- ~check that there is enough liquidity in FastExit Market Maker contract. Report to Slack if the balance is less than total value on Plasma (?)~
- check that Sniper Rifle service is operating
- check that new blocks are produced on Plasma

## Deliverables
- lambda service for monitoring is deployed and scheduled to run via cron once an hour
- 

## Size

Medium

## Roles
gardener: @troggy / 10%
worker: @troggy  / 80%
reviewer: _<empty>_ / 10%

**Comment by troggy** [comment]
Resolved here: https://github.com/leapdao/leap-peeper

deployed for testnet and mainnet, running every minute
