### ISSUE TITLE
"eventsCount expected to be x + 1" error in logs

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#132]

**Comment by sunify** [comment]
Is it related to eventsRelay? If so, it can be changed to relay transactions only from node with slot id = currentSlotId. Now all nodes try to relay events → transactions and it leads to such errors in logs

**Comment by sunify** [comment]
Basically it's the same as #127

**Comment by johannbarbie** [comment]
related, and in the same sizing: https://github.com/leapdao/leap-node/issues/127

**Comment by troggy** [comment]
via #406
