### ISSUE TITLE
Consider replacing event http polling with websocket subscription

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#133]
Leave http only for syncing past events on boot. Once started, open a websocket.

Benefits:
- no delay → faster event processing
- no empty load on the node, no need to query the root chain if no event happened

**Comment by troggy** [comment]
with web3 beta.46 I stumbled at this issue https://github.com/ethereum/web3.js/issues/2365

**Comment by troggy** [comment]
Why closed?

**Comment by johannbarbie** [comment]
ups, wrong repo, i thought this is bridge-ui
