### ISSUE TITLE
Use BigInt to compare values

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#157]
## Scope 
- rewrite all calculations and comparisons of values, ideally including `jsbi`. 

## Deliverables
- code
- tests

## Gain for the project
- ability to avoid rounding errors

## Bounty:

gardener: @johannbarbie | 10%
worker: @troggy | 80%
reviewer: @eezcjkr | 10%

**Comment by troggy** [comment]
via #155 and #160
