### ISSUE TITLE
Set up proper background process for testnet node on EC2

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#16]
Using `screen` is unbearable

**Comment by troggy** [comment]
Set up `testnet-1` and `testnet-2` with systemd.

Config: https://github.com/leapdao/leap-node/blob/master/setup/cloud/leap.systemd.service

## How to

### Change runtime arguments and ENV

```bash
sudo nano /etc/systemd/system/leap-node.service
sudo systemctl daemon-reload¹
```

### Restart

```bash
sudo service leap-node restart
```

### Check status

```bash
sudo service leap-node status
```

### Reading logs (coloring needs to be fixed)
```bash
journalctl -u leap-node --output cat -f | ccze
```

or directly from local machine:
```bash
ssh -i cyfin.pem ubuntu@testnet-2.leapdao.org journalctl -u leap-node --output cat -f
```

**Comment by sunify** [comment]
Should we have that how-to on docs?

**Comment by troggy** [comment]
yes, this could be an optional (not anyone is using systemd) setup for "Become a validator" page
