### ISSUE TITLE
plasma balance not displayed correctly

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#161]
<img width="549" alt="screen shot 2019-01-26 at 10 32 06 pm" src="https://user-images.githubusercontent.com/659301/51793027-8c1f3580-21ba-11e9-88aa-8d5c9688603c.png">

**Comment by sunify** [comment]
Is it really node issue?

**Comment by johannbarbie** [comment]
duplicate of this one: https://github.com/leapdao/bridge-ui/issues/126
i thing the state was corrupted due to BigInt rewrite

**Comment by troggy** [comment]
assuming it was a BigInt-transition glitch. Reopen when reproduced
