### ISSUE TITLE
period submission after downtime should find correct previous period or fail

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#172]
have a look at this sequence:
**a)** https://etherscan.io/tx/0xe92f1309f040193d618e9f99dc11860a1790c35f8b0e2ec1dd3419eff7c11fb7
**b)** https://etherscan.io/tx/0xda24dd54f78abca9f7a9f57c9df6677982e482c98bb3ea408dde453105b4685c
**c)** https://etherscan.io/tx/0x39e66e8b5775a8a9a7949e025e9aff579338de05782f105690d10c6409bc6655

of which c) builds on genesis. this is likely caused by the event scanner not finding the previous period and using genesis as default [here](https://github.com/leapdao/leap-node/blob/master/src/txHelpers/submitPeriod.js#L68).

**Comment by pinkiebell** [comment]
Looking at.., my first guess that we have to be smart about the eventDistance.
Using the bridgeState information, maybe :)
