### ISSUE TITLE
migrate network to latest tendermint version

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#184]
## Scope 
- upgrade tendermint dependency to v0.30 or later https://github.com/tendermint/tendermint/releases
- create upgrade procedure for network

## Deliverables
- new node release
- upgraded testnet
- upgraded mainnet (max 2 hours downtime for network)

## Gain for the project
- run latest secure software

## Roles: 
bounty gardener: @johannbarbie  / 10% 
bounty worker: name / share 
bounty reviewer: name / share

**Comment by pinkiebell** [comment]
We can also cherry-pick bug fixes, instead of merging the incompatible stuff :)

**Comment by pinkiebell** [comment]
```
--- FAIL: TestStateLockPOLRelock (0.10s)
panic: Timeout expired while waiting for NewVote event [recovered]
	panic: Timeout expired while waiting for NewVote event
```

I have flaky tests, but the same happens on the v0.31.0 branch without our changes 😬

**Comment by pinkiebell** [comment]
leap-node:
https://github.com/leapdao/leap-node/pull/217

js-abci:
https://github.com/leapdao/js-abci/tree/0.31

tendermint-node:
https://github.com/leapdao/tendermint-node/tree/0.31
