### ISSUE TITLE
create and test upgrade procedure with 0-downtime 

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#185]
## Scope 
- node upgrades should be deployable with 0 downtime for validators.

## Deliverables
- written upgrade procedure 
- code if necessary

## Gain for the project
- better xp for users and validators.

## Roles: 
bounty gardener: @johannbarbie / 10%
bounty worker: @troggy  / 75% 
bounty reviewer: name / 15%

**Comment by troggy** [comment]
my plan: 
- patch tendermint to have a switch allowing validator to work in readonly mode (no blocks produced)
- each validator should have two nodes running: one in readonly mode, another in normal mode producing blocks. Nodes should never run both in normal mode at the same time (open question how to bullet-proof ensure this)
- once there is a need to restart the node make it readonly, while making another one active (it should be in sync!). Readonly node can be restarted. Repeat for other node if needed.

progress so far:
- patched tendermint's consensus module to consider "readonly" flag. Skip `enterPropose` and some other things if it is flipped on.
- patched tendermint to expose unsafe RPC call (should be exposed only via AWS VPC, never on the internet) to flip readonly flag
-🔄verifying the setup locally. Intermediary results: readonly switch works one way so far (only "off"), node doesn't resume after flipping flag back

**Comment by troggy** [comment]
## Initial setup for 0-downtime upgrades
1. Run a validator node. ⚠️Make sure it's tendermint RPC is NOT exposed to the public internet.
2. On another machine run another node with `--config` pointing to the first node. Once started, stop the node. This is needed to create a node key and network folder. ⚠️Make sure tendermint RPC fo the second node is NOT exposed to the public internet as well.
3. Copy over `config/priv_validator.json` and `.priv` from the first node to the second node. These files are in `~/.lotion/<networkId>/` folder. This will make the second node to be validator as well (sharing the same eth and validator keys)
4. Run the second node with `--readonly` flag (see https://github.com/leapdao/tendermint/pull/1). This will allow the both nodes to stay in sync with the network, while only the one of them producing blocks
5. Setup user-facing JSON RPC load balancer/domain to point to the first node (the one without `--readonly` flag)
6. Done. As usual, keep monitoring both nodes are in sync with the network and talk to each other

## 0-downtime upgrade/restart

### Restarting both nodes
1. Make sure both nodes are in sync
2. Stop the readonly node. Do all the upgrades needed and start it again with `--readonly` flag. Wait for it to sync up. During this stage the other node should normally produce blocks and/or respond to JSON RPC requests.
3. Once readonly node is in sync, make the producing node readonly by calling `/set_readonly?readonly=true` on it's tendermint RPC. After that, make another node to start producing blocks by calling `/set_readonly?readonly=false`. In between of these calls, both nodes wont be producing blocks, so make sure the time gap between the calls is small. JSON RPC requests should be served without downtime. ⚠️You don't want to run both nodes as producing at the same time, so always start this step with setting readonly=true for producing node.
4. Change public JSON RPC endpoint to point to the producing node.
5. You can restart the readonly node now.

### Restarting only producing node

Make it readonly, then make another node to produce and serve JSON RPC (see steps 3 and 4 above). Then you can restart your node

### Restarting readonly/failover node

Just restart it :)

**Comment by johannbarbie** [comment]
reviewed by @eezcjkr
