### ISSUE TITLE
create and pulish docker image

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#193]
## Scope
- create a docker image

## Deliverables
- docker image commit
- registered organization on docker.com
- updated readme on docs.leapdao.org

## Gain for the project
- content for social 

## Roles: 
~~bounty gardener: @pinkiebell / 10%~~
bounty gardener/worker: @pinkiebell  / 70% 
bounty reviewer: @eezcjkr  / 20% | @troggy / 10%

**Comment by pinkiebell** [comment]
Track
https://github.com/leapdao/leap-node/pull/141/files
https://github.com/leapdao/leap-node/pull/137
