### ISSUE TITLE
Investigate: block height in database does not match block height in query via db.getTransaction

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#208]
<img width="1440" alt="Screenshot 2019-03-15 at 17 43 12" src="https://user-images.githubusercontent.com/40266861/54447691-51616480-474a-11e9-9662-ff2c2d12a9ed.png">

**Comment by troggy** [comment]
👀

**Comment by troggy** [comment]
cannot reproduce.

Executing `GET 'tx!0x22151f6712423ca2f3c31267d8bc035e25cf37bc305ea1620a5704fd7982ba23'`on LevelDB:
```
{"txData":{"type":2,"hash":"0x22151f6712423ca2f3c31267d8bc035e25cf37bc305ea1620a5704fd7982ba23","inputs":[],"outputs":[{"address":"0x6cb117a635dc7633b42089c607fdfc5c60b7d679","value":"5000000000000000000","color":0}],"options":{"depositId":1}},"blockHash":"0xdd95b5693c4ce15d6d812a41186410806844643fa15e958edda6663b2011b371","height":5,"txPos":2}`
```

Executing `db.getTransaction('0x22151f6712423ca2f3c31267d8bc035e25cf37bc305ea1620a5704fd7982ba23')`:

```
{"txData":{"type":2,"hash":"0x22151f6712423ca2f3c31267d8bc035e25cf37bc305ea1620a5704fd7982ba23","inputs":[],"outputs":[{"address":"0x6cb117a635dc7633b42089c607fdfc5c60b7d679","value":"5000000000000000000","color":0}],"options":{"depositId":1}},"blockHash":"0xdd95b5693c4ce15d6d812a41186410806844643fa15e958edda6663b2011b371","height":5,"txPos":2}
```

@pinkiebell where the 75 on your screenshot coming from?

**Comment by pinkiebell** [comment]
@troggy This was on goerli but I upgraded since then. The `75` is the requested height, and I had `73` in the `db`, it was the right transaction, but the blockHeight inside `txData` was wrong 🤷‍♂️

**Comment by troggy** [comment]
> The 75 is the requested height,

what's "requested height" ? How did you "request" it? JSON RPC (`getBlockByHeight`) ?

**Comment by pinkiebell** [comment]
> > The 75 is the requested height,
> 
> what's "requested height" ? How did you "request" it? JSON RPC (`getBlockByHeight`) ?

Either that or with getBlockByHash or something. Not quite sure anymore 😅

**Comment by troggy** [comment]
Cannot reproduce.

Checked by calling JSON RPC directly on the node (skipping web3/client part).

Like:
```
curl -X POST \
  http://localhost:8645/ \
  -H 'Content-Type: application/json' \
  -d '{
  "method": "eth_getBlockByHash",
  "params": [17, true],
  "id": 1,
  "jsonrpc": "2.0"
}'
```
