### ISSUE TITLE
move every script/tool you use for debugging or tinkering to ..

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#210]
... into the `leap-guardian` repo, if applicable.

That way we have a common repo of useful scripts 😄

**Comment by johannbarbie** [comment]
here is another one: https://github.com/leapdao/leap-node/blob/master/src/utils/claimRewards.js

**Comment by pinkiebell** [comment]
> here is another one: https://github.com/leapdao/leap-node/blob/master/src/utils/claimRewards.js

❤️ Care to put it into leap-guardian? 🙂

**Comment by johannbarbie** [comment]
👌

**Comment by troggy** [comment]
I think this one can be closed? @pinkiebell

**Comment by pinkiebell** [comment]
@troggy Of course 👍
