### ISSUE TITLE
Do not replay all the blocks on restart

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#212]
See https://leapdao.slack.com/archives/C89PMGK7U/p1552659070005600?thread_ts=1552642749.000100&cid=C89PMGK7U

- persist app state (bridgeState + state)
- implement ABCI `Info` and return proper `LastBlockHeight` (see latest lotion version)

## Gain for the project
- faster restarts, less entropy

**Comment by pinkiebell** [comment]
Postponed for a later time

**Comment by troggy** [comment]
I think we need to solve this as soon as possible — with the network growth, restarts take more and more time. Makes in hard to maintain networks

**Comment by sunify** [comment]
https://github.com/tendermint/tendermint/blob/80d0a362500fea2dd089258319075a54e5d40a2d/docs/app-dev/app-development.md#handshake

https://github.com/tendermint/tendermint/blob/b771798d48c27630fb37b74c8e229da5a8b2042c/docs/spec/abci/abci.md#info

We need:

1. Store state somewhere (leveldb?)
2. Read it on restart
3. Provide lates height and app hash in info response
4. ???
5. PROFIT!

**Comment by pinkiebell** [comment]
@johannbarbie What do you think?
If that does not eat much time, we could take it back into the sprint I guess?

**Comment by pinkiebell** [comment]
Oh shit, missed that thing here

**Comment by troggy** [comment]
fixed by #241
