### ISSUE TITLE
Performance goal for transfers

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-node#214]
Parameters:
1. Test 1:
   * Arrival count: 1 user per second
   * Actions by user: 1 transfer
   * Duration: 4000 seconds (i.e. 4000 transactions total)

1. Test 2:
   * Arrival count: 10 user per second
   * Actions by user: 1 transfer
   * Duration: 60 seconds (i.e. 600 transactions total)

1. Test 3:
   * Arrival count: 50 user per second
   * Actions by user: 1 transfer
   * Duration: 10 seconds (i.e. 500 transactions total)

Success criteria:
* Max wait time for transaction to be included: 10 seconds
* Median wait time should not exceed 3 seconds
* Min success rate: 99%

Additional metrics to measure:
* Transactions per block
* Number of blocks needed
* block distance less than 2 seconds (single operator)

**Comment by troggy** [comment]
supposedly fixed by #241. Needs to be rechecked on the latest node

**Comment by eshavkun** [comment]
Updated description.
A lot of users (towards the end of test) get wait times of 10 seconds or more. See #213 for details

**Comment by johannbarbie** [comment]
old
