### ISSUE TITLE
Detach leap-node from the root network provider url

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#227]
We want people to run the node using their own providers. Now, when you spin up a testnet node it will take a root network id from the config, but still will use hardcoded provider URL (infura).

**Scope:**
- add an optional `providerUrl` cli argument
- on start, check that given provider is for the same network (compare with `rootNetworkId` from the network config)
- ~if not specifed, fallback to LeapDAO's Infura (questionable, should we do that?)~

**Size:**
XXS

**Comment by troggy** [comment]
question here: should we keep infura urls in the repo at all.

Pros: easier for us to start the nodes
Cons: no incentive to use your own infrastructure

**Comment by pinkiebell** [comment]
> question here: should we keep infura urls in the repo at all.

I say no. Let's remove them. Not that someone uses it and we change the infura  account and someone get's bite'n by that.

**Comment by troggy** [comment]
via #352
