### ISSUE TITLE
Keep a log of included transactions which get pruned after some time...

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#228]
needed for https://github.com/leapdao/burner-wallet/issues/1

**Comment by troggy** [comment]
why would we need to keep the log of *included* transactions? For 'success' receipts we can just take included transactions from the database. We may need this log for 'failed' transactions, or am I missing something?

**Comment by johannbarbie** [comment]
outdated, fixed by pulling block inclusion
