### ISSUE TITLE
Should getBalance accept another parameter which stand for 'color'

### ISSUE THREAD

**Issue by zyfrank** [leapdao/leap-node#229]
I notice getBalance just support color '0' ,  why not supporting other color balance?

**Comment by troggy** [comment]
@zyfrank we want to be compatible with Ethereum JSON RPC as much as possible

Colors are ERC20 tokens, so to get balance use `balanceOf` function of ERC20

**Comment by zyfrank** [comment]
@troggy  I see, thanks for information provided
