### ISSUE TITLE
Submit the merkle-root hash of all UTXO/unspent states in submitPeriod

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#232]
# Bounty
Required for the Computation Verification Game
Todo... write more info
## Scope

-
-
-

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by pinkiebell** [comment]
@eezcjkr @johannbarbie @troggy @eshavkun @sunify

**Comment by johannbarbie** [comment]
i don't think this is needed, you always get the UTXO that is needed by submitting the current tx, and the previous tx, and the validate like here: https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L83-L104

**Comment by pinkiebell** [comment]
True 😄
