### ISSUE TITLE
Change validator EC to secp256k1

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#233]
# Bounty
Currently we are using `ed25519`, tendermint supports `secp256k1` now.
We should use that to save some bits in the contracts and node-network.

## Scope

- Change leap-node to work with `secp256k1` instead of `ed25519` for validator updates.
- Change the leap-contracts to reflect the changes.
- Change any tests/tools which rely on the validator pubKeys.

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by pinkiebell** [comment]
@johannbarbie 
Seems like we don't really save anything 🤔 
The only thing there we can save some storage is to not save the `tenderKey` into storage but just emit it in the logs.

Or did you have another use-case on mind?

**Comment by troggy** [comment]
obsolete probably

**Comment by johannbarbie** [comment]
wouldn't we save all the logic in the node to manage the signer key. also if validators use an HSM, they can just follow the tendermint docs. 🤔
