### ISSUE TITLE
Upgrade to tendermint v0.31.7

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#234]
# Bounty
This includes security related fixes.

## Scope

- Upgrade our tendermint fork to v0.31.7
- Integrate the new release into leap-node

## Roles
bounty gardener: @troggy / 10%
bounty worker: @pinkiebell  / 60%
bounty reviewer: @troggy  / 30%

**Comment by troggy** [comment]
@pinkiebell I suggest we change this one to upgrade to 0.31.7. Version 0.13.6 contains breaking changes and it would be good to incorporate those before mainnet migration. 👍👎?

**Comment by troggy** [comment]
Changelog: https://github.com/tendermint/tendermint/blob/v0.31/CHANGELOG.md#v0317

**Comment by pinkiebell** [comment]
@troggy Sure 👍 .
Btw, I guess the breaking changes are not consenus related, just the api. We should be fine with upgrading to 0.31.7 on current testnet I guess

**Comment by troggy** [comment]
>  I guess the breaking changes are not consenus related, just the api.

good point

**Comment by pinkiebell** [comment]
@troggy 

Seems like we can remove the `breaking` label 😎
