### ISSUE TITLE
Umbrella issue 

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#235]
# Bounty

leap node: ~#222~ → #241
Integration tests: https://github.com/leapdao/integration-tests/pull/28

Related Issues: #214 #212 

## Deliverables

- Higher node performance in both startup and delivering txs into a block.
- Removing some technical debt
- Breaking changes are not included, that will be handled in a different branch
- integration tests are faster to start now and flaky-ness is reduced greatly

## Gain for the project

Gain is removal of some Pain

### Publicly visible delivery

We can claim good housekeeping and a faster plasma chain.

## Roles
bounty gardener: @pinkiebell  / 5%
bounty worker: @pinkiebell  / 70%
bounty reviewer: @troggy  / 25%

**Comment by troggy** [comment]
closed by #241 and leapdao/integration-tests#28
