### ISSUE TITLE
support deposit, update and exit of NSTs

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#238]
# Bounty

## Scope

related:
https://github.com/leapdao/leap-core/issues/80
https://github.com/leapdao/spending-conditions/issues/8
https://github.com/leapdao/leap-contracts/issues/168

## Deliverables

- ability to hold storage roots in state
- support update of storage by spending conditions
- enforce updates by owner only

## Gain for the project

- distributed breeding

### Publicly visible delivery

- update of docs

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: name / 70%
bounty reviewer: name / 20%

**Comment by pinkiebell** [comment]
![Photo on 15 04 19 at 13 21](https://user-images.githubusercontent.com/40266861/56128946-556ae700-5f81-11e9-97f8-e1a4ac85114d.jpg)
