### ISSUE TITLE
No periods submitted after switching the node from readonly to operating

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#251]
Happens due to this check: https://github.com/leapdao/leap-node/blob/master/src/txHelpers/submitPeriod.js#L54

It always checks the `nodeConfig.readonly` which is only the initial state. The actual switchover happens via tendermint RPC (see #185), which doesn't affect leap-node.

Suggested fix: query `status` endpoint of tendermint RPC here to get `is_readonly` value

Temporary workaround: do not start the node in readonly mode (easy with fast restart since 4.4.0)

**Comment by troggy** [comment]
On a side note: #212 makes the whole 0-downtime upgrade procedure obsolete

**Comment by troggy** [comment]
@pinkiebell FYI. Relevant for mainnet

**Comment by troggy** [comment]
maybe not a good idea to run [this](https://github.com/leapdao/leap-node/commit/064c2844318bde7da2f149eb7ec553e87c70df88) on mainnet as it seems to break 0-downtime upgrade routine 🤔

**Comment by pinkiebell** [comment]
@troggy Yep. Already accounted for that. Thanks for the info tho 👍

**Comment by troggy** [comment]
obsolete. Not going to use this anymore
