### ISSUE TITLE
Implement `eth_getCode` for ERC{20,721,1948}

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#257]
# Bounty
Implement `eth_getCode` rpc call, we already have the bytecode in our repo, we just need to check color and return the bytecode
## Scope

-
-
-

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by johannbarbie** [comment]
why not just proxy to contract on main-net?

**Comment by pinkiebell** [comment]
> why not just proxy to contract on main-net?

You mean also for other calls? Dont know why we should do that. User could just use 2 providers

**Comment by pinkiebell** [comment]
Nvm, I was out of context. We should only return contract bytecode we actually 'have' 🤸‍♂️

**Comment by johannbarbie** [comment]
i guess i simply don't understand what this call is doing and why it is needed :)

**Comment by troggy** [comment]
@pinkiebell @johannbarbie are you guys in consensus about this change? Because it appears in the `staging` branch
