### ISSUE TITLE
add support for PERIOD_VOTE tx type

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#282]
## Bounty

period vote transaction are used by validators to signal on data availability of 32-block chunks.

## Scope

- enable node to handle [period vote txns](https://github.com/leapdao/leap-core/blob/master/lib/transaction.js#L74)
- in [check bridge](https://github.com/leapdao/leap-node/blob/master/src/period/index.js), replace period submission with broadcast of periodSubmision txns
- in [check bridge](https://github.com/leapdao/leap-node/blob/master/src/period/index.js), build CAS bitmap and submit period if >2/3 of periodVotes available

## Deliverables
- code 
- tests

## Gain for the project
- ability to run PoS

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by pinkiebell** [comment]
Looks good. Interesting would be the case if we can't get 2/3 of votes for the period. How is that handled? Chain stops and waits or just move on?

**Comment by troggy** [comment]
Integration tests are out of scope and to be done here: https://github.com/leapdao/integration-tests/issues/39

**Comment by troggy** [comment]
I've found a non-determinism in multi-validator setup: validators disagree on a few blocks per period, leading to different period roots. 
This seems like a time sink, so I’d like to remove period submission from the scope of this bounty
