### ISSUE TITLE
create an index for transactions by prevOut

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#283]
## Bounty

for exit challenges we need to be able to query all transactions by prevOut (hash + output index). for CAS challenges the same index can be used, as the PERIOD_VOTE transaction puts the periodHash into the input.

## Scope

- create index for all included transactions by `prevOut`
- provide API to query any transactions by `prevOut`
- provide API to query periodVote transactions by `prevOut`

## Deliverables

- code
- tests

## Gain for the project

- ability to run multiple validators

### Publicly visible delivery

- extend documentation with api endpoint

## Roles
bounty gardener: @johannbarbie / 15%
bounty worker: @troggy  / 65%
bounty reviewer: name / 20%

**Comment by troggy** [comment]
@johannbarbie still free for grabs? I'm up for it
