### ISSUE TITLE
Immediately exclude exiting UTXOs from the active set

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#284]
# Bounty

**Problem**

Delay in eventRelay for Exits may lead to double spends

Consider:
1. User has UTXO A
2. User starts an exit for A. ExitStarted event is on the root chain, but bridge state is not changed yet due to delay in eventRelay
3. User does UTXO consolidation or otherwise spends A. At this point A is still in his UTXO set because Exit transaction is not yet created.
4. EventRelay finally processes ExitStarted event, creates and broadcasts Exit transaction
5. Exit transaction gets rejected because it refers to spent UTXO (`checkExit`).

Result: plasma chain thinks UTXO was transfered (no Exit tx), bridge has an invalid exit registered.

This bug is easily reproduced with our Bridge UI — exited UTXO is even visible for a while (until UTXO set changes).

**Proposed mitigation**

Let's collect exiting UTXOs on the node side without consensus delay and use the collected set to filter the results of `getUnspent` RPC. The assumption here is that the node is relatively good with keeping up with the root chain tip.

This is just a one of the possible solutions to _reduce_ the possibility of the problem to occur. Worker is free to propose a better solution.

## Scope

- add additional handler for ExitStarted event which processes the event without delay. Use this handler to collect exiting UTXOs. Collected UTXOs shouldn't be a part of the node state, as they are not consensus-safe.
- change `getUnspent` JSON RPC to filter out exiting UTXOs from the result set
- update docs
  - add a "Plasma Bridge" page to the docs.leapdao.org describing how to implement deposit and exit in a dapp
  - documentation for Exits should emphasise that the dapp should be careful not to use exited UTXO at least before the remote node "seen" it (e.g. by polling `getUnspents` for the address)

## Deliverables

- updated leap-node
- updated docs.leapdao.org

## Gain for the project

less error-prone dapps

### Publicly visible delivery

- new "Plasma Bridge" page on docs.leapdao.org

## Roles
bounty gardener: @troggy / 50 DAI
bounty worker: @troggy / 75%
bounty reviewer: name / 25%

## Funded by

Dev Circle

**Comment by pinkiebell** [comment]
The problem with consistency with the parent-chain is a tough one.
We can try to make the event handling more robust and more aggresive, means we can use a model like chained task queues. We can also use more than one provider but at the end we only improve the situation not eliminating it.

We could introduce a `EXIT_QUEUED` tx type, but only as optional measure. Any user could just exit directly via contracts and we get the same problem.

**Comment by troggy** [comment]
I suggest to
1. alleviate this issue on a client side, by keeping track of "exiting" UTXOS in a leap-core/leap-provider and filtering them out from `getUnspent` call result.
2. additionally keep track of exit events without event buffer. This data is to be used only to filter out exiting utxos from `getUnspent` response. For consensus, event buffer is still to be used.
3. It should be emphasized that it is a responsibility of client developers to keep track of exiting UTXOs.

**Comment by johannbarbie** [comment]
> 2. 

keep track where? client side? node side?

**Comment by troggy** [comment]
@johannbarbie node side. Of course, this is not a "solution" as the exiter may use another node (sentinel!), just reducing the probability of accidental UTXO reuse.
Using `EXIT_QUEUED` tx type as @pinkiebell proposed would be even better 🤔
