### ISSUE TITLE
enable a poor-man's heartbeat monitor

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#288]
## Bounty

**Problem:**
- when a validator [applies for a slot](https://docs.google.com/forms/d/e/1FAIpQLSdQtc5LoEyWkc5-86SOLW3xK8cRNwuByC7SIrA9MdWeAiuBZw/viewform), signer address and tendermint key are provided.
- before giving a slot to a validator, it is recommended to check that the node is operational. that includes:
  - signingKey is funded (can be checked on etherscan)
  - node is connected to network (**currently no way to check**)
  - node is synced to the top of the chain (**currently no way to check**)

**Invalid approaches:**
- simply ignoring availability of a validator poses a risk to the liveliness of the Leap Network.
- any solutions involving access to the validator's RPC are miss-guided, as for DoS protection validator RPC should be kept offline.

**Proposal:**
- a heartbeat UTXO is defined as a NFT of dedicated color.
- if a heartbeat UTXO is present on it's signer Address, a synced node will "push it forward" every 1 minute by spending it into a new UTXO(similar to sniper riffle).
- to prevent fake heartbeat construction without running a node, there should be an option for public nodes to filter out heartbeat UTXOs from `getUnspent()` RPC responses.

## Scope

- implement a service that submits heartbeats once a minute from node, if UTXO present.
- add a heartbeat-filter param to config parameter, by default set to `true`.
-  change getUnspent API to exclude heartbeat color

## Deliverables

- update code
- updated tests

## Gain for the project

during the validator signup procedure the following uptime test can be executed:
  - check if applicant signer address is already funded with heartbeat UTXO, if not, fund it.
  - monitor the heartbeat for x hours in bridge-ui
  - assign a slot, if uptime has been maintained for duration of test.

the following features can be added later with little effort:
- script that monitors heartbeats and automatically empties dead slots during PoA
- challenge function on PoS contract that slashes slots for downtime. 

### Publicly visible delivery

- describe new config field in docs
- add a section about heartbeats to Q&A

## Roles
bounty gardener: @johannbarbie + @troggy / 10%
bounty worker: @vrde / share
bounty reviewer: name / share

## Funded by

Dev Circle

**Comment by troggy** [comment]
> to prevent fake heartbeat construction without running a node, there should be an option for public nodes to filter out heartbeat UTXOs from getUnspent() RPC responses.

Maybe we can have a Heartbeat ERC721 ?

**Comment by troggy** [comment]
> signingKey is funded (can be checked on etherscan)
> node is connected to network (currently no way to check)
> node is synced to the top of the chain (currently no way to check)

Agree this should be checked.

However, I don't understand how UTXO pushing will ensure that?

**Comment by troggy** [comment]
I see that there are two problems:
1. How to ensure the validator is setup correctly before we give it a slot (one time action)
2. How to make sure onboarded validator is working correctly (monitoring, recurring action)

Here we want to address only the first one, right?

**Comment by johannbarbie** [comment]
> how UTXO pushing will ensure that?

to construct a valid transaction with inputs that are close to the tip of the chain, one needs to be synced to the tip of the chain.

ideally there is some proof of data availability, but a poor man's solution is just to filter out relevant data from  the `getUnspent()` from public API's that we provide.

**Comment by johannbarbie** [comment]
> Here we want to address only the first one, right?

yes, because it is a problem we are facing now. but we need to have a design in the pocket, because the other problem will appear right after we have first validators running.

**Comment by vrde** [comment]
I'll do it

>

**Comment by johannbarbie** [comment]
resized to M in conversation with @MaxStalker
