### ISSUE TITLE
create a periodStore in node

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#289]
## Bounty

any service that requires inclusion proofs (bridge UI for exit, challengers) needs period information. currently there is a complex procedure to fetch all transactions from a range of blocks and assemble them in the right way, then sprinkle some slot data on top, and get your proof.

this bounty is meant to simplify this work, and create an API endpoint on the node where any client can fetch period data by block height.

`GET_PERIOD(block_Number)` will return:

```
[{
  "startBlock": 123,
  "endBlock": 123,
  "slotId": 123,
  "validatorAddr": "0x123",
  "blockRoots": ["0x1234", ..32],
  "txHashes": ["0x1234", ...] // for block 
  },{multiple periods can be submitted at the same height}
]
```

## Scope

- create a database that stores period information: validator, slotId, height, CAS bitmap
- feed database from period submission events
- create API endpoint to get period data

## Deliverables

- code
- tests

## Gain for the project

- ability to run multiple validators

### Publicly visible delivery

- update docs page with new api endpoint

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @troggy / 70%
bounty reviewer: name / 20%

**Comment by troggy** [comment]
I'm putting this one back to CAS sprint as a subset of this is needed for https://github.com/leapdao/exit-market-maker/issues/9 and https://github.com/leapdao/integration-tests/issues/20
