### ISSUE TITLE
Cannot change epoch length

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#310]
# Bounty

**Given:**
Testnet with two validators and epochLength set to 4.
Governance proposal `setEpochLength(2)` is submitted and finalized.
`EpochLength` event lands on the root chain.
`PoaOperator.epochLength` is changed to 2.

**Expected:**
Epoch length in leap-node's `bridgeState` is changed to 2.

**Actual:**
Epoch length in leap-node's `bridgeState` remains equals to 4. `leap-node:error Unknown epochLength change` error in logs

## Scope

- find and fix a root cause for described issue

## Deliverables

- updated code and tests

## Gain for the project

properly working epochLength setup

### Publicly visible delivery

🤷‍♂ 

## Roles
bounty gardener: @troggy / 30 DAI
bounty worker: @sunify / 80%
bounty reviewer: @iamonuwa + @troggy  / 20%

## Funded by

EF

**Comment by troggy** [comment]
https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkEpochLength.js#L15-L17

**Comment by sunify** [comment]
![image](https://user-images.githubusercontent.com/1477583/62719063-bab77c00-ba39-11e9-9ba0-a4f474e9f3cf.png)

🤔 can't reproduce this. Tried with unit tests on the node side and with intergration tests, but it seems to work fine

Any clues how to reproduce?

**Comment by troggy** [comment]
I don't know :(

it happens right now on the testnet — tried couple of times. Probably depends on the current state and bridgeState. I think it should be possible to restart one of the sentinels with `--inspect` and check the state

**Comment by sunify** [comment]
Cool, thanks. Will try tomorrow

**Comment by troggy** [comment]
I can quite stable reproduce the problem with integration tests running against feat/support-period-vote and latest leap-contracts.

Attached the logs for both nodes. You can see that on block 10 node 1 rejected EpochLength(2) event, while the node 2 accepted. Result — consensus error on block 11.
[node-1.log](https://github.com/leapdao/leap-node/files/3486621/node-1.log)
[node-2.log](https://github.com/leapdao/leap-node/files/3486622/node-2.log)

**Comment by troggy** [comment]
Added this one to CAS project, it is essential

**Comment by sunify** [comment]
Ok. I've run this so many times, but no luck. Also, I noticed `Check: undefined` and `tx: undefined` entries in your logs. I suppose it was period vote transactions. Are you sure you were running integration tests against period-vote branch?

The only thought why it can happen:
EPOCH_LENGTH tx broadcasted before node read the event from contract so bridgeState doesn't know about this change. But i thought it was resolved by eventRelay

**Comment by troggy** [comment]
which version of integration tests have you used? The error was "fixed" by this commit https://github.com/leapdao/integration-tests/commit/01434960c83bde9bda82b422603481224edf2202, though still should be reproducable on any commit prior to this one. I will try to reproduce again

**Comment by sunify** [comment]
Yes, i know that. I've commented this line out before running the tests. Also, I've changed integration-tests branch in travis: https://github.com/leapdao/leap-node/pull/312/commits/7ff54b1b6f9d63ec6163606bff756dbb02b8d601. Works fine as well

**Comment by troggy** [comment]
> I suppose it was period vote transactions

it could not be so as period votes tx are created only on height 32 and the failure happens much earlier

**Comment by troggy** [comment]
Other side effect of this issue: you cannot sync with testnet anymore, it always rejects the very first EpochLength event and thus tendermint panics at block 4.

**Comment by troggy** [comment]
suggested to change funding to EF

**Comment by troggy** [comment]
I've stumbled upon another issue:
1. Run the local env (integration tests with `yarn start`). This will spin up two validator network with epoch length of 2.
2. Try to change epoch length to 3: submit and finalize a proposal to MinGov.
3. You get `leap-node:error Wrong epoch length` in logs and epoch length stays 2

**Comment by troggy** [comment]
opened another issue to followup on this — #340
