### ISSUE TITLE
Fix network configuration

### ISSUE THREAD

**Issue by vrde** [leapdao/leap-node#352]
# Bounty

## Scope
Fix configuration issue described in #347.

## Deliverables
A fix for the bug :)

## Gain for the project
- Better network handling. Before a `chainId` was bound to a specific JSONRPC endpoint on infura or to a specific network address.
- Less confusion for developers trying to run a node or connect to other nodes.

## Roles
bounty gardener: @vrde / 10%
bounty worker: @vrde / 70%
bounty reviewer: name / 20%

**Comment by troggy** [comment]
Duplicates https://github.com/leapdao/leap-node/issues/227
