### ISSUE TITLE
Get rid of CheckBridge and forked Tendermint

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#357]
# Bounty

We are using tendermint fork with extra home-grown ABCI called `CheckBridge`. It is supposed to be called every 32 blocks and return 1, otherwise the [proposal is deferred](https://github.com/leapdao/tendermint/blob/ac73b47182d5cb018db31f02e49ad0a336f4473f/consensus/state.go#L893) (consensus engine is stopped). On a leap-node side we use [checkBridge handler](https://github.com/leapdao/leap-node/blob/5c84024769954b262eca48ff8660ae5efe3aad01/src/period/index.js#L12) to ensure there is a period submitted. This is the ultimate reason for all the clusterfuck — ensure that period is submitted.

~Three~ One problem with this approach:
1. We need forked tendermint, which makes sync with upstream harder.
2. ~It won't be working right because of the CAS — there is no period every 32nd block anymore with CAS — it is submitted later, once there are enough period votes.~ Solved in #358
3. ~As of now it [doesn't seem to work](https://github.com/leapdao/leap-node/issues/326) yet the networks are working.~ Solved in #358

This bounty attempts to address the problem purely on ABCI app side, so we can use vanilla tendermint.

## Scope

- once a period is submitted, add `[periodMerkleRoot;prevPeriodHash;txHash;slotId]` tuple to the `pendingPeriods` list in the bridgeState. If the list was empty store submission time in `bridgeState.periodSubmissionTime`.
- create a block middleware to take the first item from the `pendingPeriods` and check if the period is landed on the root chain. Skip if the current node is not a validator or `slotId` of the pending period is not matching the node's slot.
     - If the period is on the root chain, remove the item from the `pendingPeriods` list. If `pendingPeriods` is not empty, set `periodSubmissionTime` to the current time.
     - if the period submission failed (e.g. due to out of money) — resubmit the transaction and update `periodSubmissionTime`
     - If the period is not on the root chain yet (tx is not mined), check `periodSubmissionTime` — if it is older then 10 minutes, resubmit the period transaction with higher gas price.
- use vanilla tendermint (stick to version 0.31.7 for starters — this is the one we've forked)
- test scenarios:
  - multiple periods submitted one-by-one
  - underpriced period submission is resubmitted successfully
  - resubmission stuck as well and it is time to submit a next period — eventually both are submitted successfully
  - submission stuck, node restarted → submission tracking should resume
- make sure integration tests are passing

## Deliverables

- updated leap-node
- writeup about the change (for peeps and for newsletter)

## Gain for the project

- easier code base (no forked tendermint)
- underpriced period resubmissions

### Publicly visible delivery

writeup for newsletter

## Roles
bounty gardener: @troggy / 90 DAI
bounty worker: name / share
bounty reviewer: name / share

**Comment by johannbarbie** [comment]
how to prevent that tendermint runs too far ahead of period submission?

**Comment by sunify** [comment]
Why it is bad? (asking for a friend)

**Comment by troggy** [comment]
> how to prevent that tendermint runs too far ahead of period submission?

I can imagine it is possible to have temporary gaps in a period lists. We are not really chaining periods anyway — `prevHash` in Period object is not used anyhow. Or am I missing something?

**Comment by johannbarbie** [comment]
> Why it is bad?

- can't construct proofs
  - fast exit handler can become veeery slow
- unordered submission problems
- ~parallel submission problems~

**Comment by johannbarbie** [comment]
> prevHash in Period object is not used anyhow

- used [here](https://github.com/leapdao/leap-contracts/blob/master/contracts/Bridge.sol#L83)
- `prevHash` will be critical to implement `block.timestamp`/`now` in Plasma runtime

**Comment by pinkiebell** [comment]
I think a threshold of max. 3 pending periods cause no problems?

> As of now it doesn't seem to work yet the networks are working.

That's odd. 🤔 The last time I had the leap-node running, I had those checkBridge call in the debug logs.

**Comment by troggy** [comment]
ok, we keep `prevHash` :) doesn't really stops us from having some temporary gaps

**Comment by troggy** [comment]
also, @sunify and me discussed an option to "suspend" the app if there is no period landed after 32 blocks. Similar like we do with CheckBridge, but done on the app side: just need to stop proxying txs to Tendermint RPC.

**Comment by troggy** [comment]
> unordered submission problems

@johannbarbie you mean tracking of nonce?

**Comment by johannbarbie** [comment]
> > unordered submission problems
> 
> @johannbarbie you mean tracking of nonce?

i was only referring to `prevHash`

**Comment by pinkiebell** [comment]
> also, @sunify and me discussed an option to "suspend" the app if there is no period landed after >  Similar like we do with CheckBridge, but done on the app side: just need to stop proxying txs to Tendermint RPC.

What if a malicious- or bad node sends to the tendermint daemon? 🙂 

Edit:
I think implementing a method to completely halt the consensus and/or mempool engine would work

**Comment by troggy** [comment]
> to completely halt the consensus

that's what we doing with CheckBridge. @pinkiebell Do you know how to do that without changing Tendermint code?

**Comment by pinkiebell** [comment]
> > to completely halt the consensus
> 
> that's what we doing with CheckBridge. @pinkiebell Do you know how to do that without changing Tendermint code?

Sadly, no idea. you can check the ABCI endpoints but I'm sure something like that isn't there.
Another idea without running a fork is to kill the tendermint daemon and restart once periods looking fine 😁

**Comment by troggy** [comment]
> It won't be working right because of the CAS

maybe I've over-exaggerated — checkBridge checks not the current, but the previous submission which should happen at that point even with CAS.

**Comment by troggy** [comment]
> unordered submission problems

I think this is solved, if all the validators keep a pendingPeriods list — proposer can just use the hash of the last period as a prevHash.

**Comment by johannbarbie** [comment]
overall gut feeling:
- super scared that it will break in unforeseen ways
- happy to trust you guys with the architecture decision

:)

**Comment by troggy** [comment]
> can't construct proofs
> fast exit handler can become veeery slow

Both of these are relevant right now as well: if there is no period and checkBridge stops the consensus you can't construct proofs as well.

**Comment by troggy** [comment]
> super scared that it will break in unforeseen ways

Me too. I also scared that the node is _working_ in unforeseen way 😄

**Comment by troggy** [comment]
I see two quite separate concerns here in this issue:
- checking that periods are landed on the root chain
- using patched tendermint to stop the consensus in case if period submission didn't happen in time

The bounty definition as it is now addresses only the first concern assuming the second one is not needed and should be removed. While it is still not clear should we allow the chain to run once there are missed period submissions, I will split this bounty in two:
1. More reliable period tracking (like described in this bounty). We can keep patched Tendermint and checkBridge feature.
2. Replace checkBridge hack with something on the app side (this is to be defined) or remove the hack completely. Switch to upstream vanilla Tendermint.

**Comment by troggy** [comment]
closing in favour of https://github.com/leapdao/leap-node/issues/410

+ https://github.com/leapdao/leap-node/blob/master/docs/tendermint.md
