### ISSUE TITLE
preserve pending periods in between restarts

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#359]
# Bounty

leap-node keeps track of the current period object: new one is [created](https://github.com/leapdao/leap-node/blob/5c84024769954b262eca48ff8660ae5efe3aad01/src/block/updatePeriod.js#L55) every 32 blocks and [filled](https://github.com/leapdao/leap-node/blob/5c84024769954b262eca48ff8660ae5efe3aad01/src/block/addBlock.js#L15) with mined plasma blocks. When it is time to create a new period, we [save](https://github.com/leapdao/leap-node/blob/5c84024769954b262eca48ff8660ae5efe3aad01/src/block/updatePeriod.js#L54) the current one into `bridgeState.previousPeriod` so that later we can check if it is landed on the root chain or not. We do this check in a [period handler aka checkBridge](https://github.com/leapdao/leap-node/blob/5c84024769954b262eca48ff8660ae5efe3aad01/src/period/index.js#L12). If the check fails, we [stop](https://github.com/leapdao/tendermint/blob/ac73b47182d5cb018db31f02e49ad0a336f4473f/consensus/state.go#L902) the consensus engine until the period is on the root chain.

The problem is that `bridgeState.previousPeriod` is created only in a block handler. If we restart the node, `bridgeState.previousPeriod` will be lost as block handler for that particular height won't be executed anymore (unless we rollback the local data or resync the chain). No `previousPeriod` — no ability to check if it is landed on the root chain. Essentially, in this situation period handler will just [skip](https://github.com/leapdao/leap-node/blob/5c84024769954b262eca48ff8660ae5efe3aad01/src/period/index.js#L19) the check with `ok` and we lost the period.

## Scope

- store both `previousPeriod` and `pendingPeriod` in the db (see `bridgeState.saveSubmissions` for example, no need to do it every block though, only once created). It should be enough to store only period merkle root and prevHash.
- read stored values on a startup
- test scenarios:
   - node makes underpriced submission, node is stopped and resumed — checkBridge should figure out the submission and succeed
    - checkBridge can't find the submission and awaits, node is stopped and resumed — checkBridge should continue awaiting until the period is on chain
- make sure integration tests are working
- add unit tests

## Deliverables

- updated code
- updated tests

## Gain for the project

reliable node restarts, no lost submissions

## Roles
bounty gardener: @troggy / 70 DAI
bounty worker: @troggy / share
bounty reviewer: name / share

## Funded by

Dev Circle

**Comment by troggy** [comment]
upsizing to M

**Comment by johannbarbie** [comment]
what if a node starts a lot later, when the preserved period has no relevance any more. is that case covered?

**Comment by troggy** [comment]
> has no relevance any more

how is that? If it wasn't submitted, it is still relevant, no? If it was submitted by someone else it will be handled during event replay (see Submission handler in bridgeState)

**Comment by johannbarbie** [comment]
> it will be handled during event replay (see Submission handler in bridgeState)

that is what i wanted to know :)
