### ISSUE TITLE
Error when installing node on Windows 10

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/leap-node#376]
# Bounty
Tried to set up my node on a Windows Laptop with Windows 10. Got the following error.

## Deliverables

bug: 
![Validator Error Windows 10](https://user-images.githubusercontent.com/45236782/70822615-3fe2e100-1dde-11ea-89c7-b2d92234c17a.png)

## Gain for the project

Setting up testnet node

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by troggy** [comment]
more details needed
