### ISSUE TITLE
Read heartbeat token color from Operator contract

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#413]
# Bounty

There is a heartbeat service in leap-node. It periodically publishes a transfer tx for Heartbeat NFT token to signal liveness of the node. Heartbeat NFT is a normal ERC721 token, registered with Leap Network Plasma contract as usual. All tokens registered on Leap Network receive a `color`, a number by which you can address the token on plasma network.

Currently, a color for heartbean token is specified [as a node option](https://github.com/leapdao/leap-node/blob/master/src/heartbeat/index.js#L30). This is redundant and error-prone as the heartbeat color is already specified [in operator contract](https://github.com/leapdao/leap-contracts/blob/master/contracts/PoaOperator.sol#L332).

## Scope / What's need to be done

- change the heartbeat configuration logic to read heartbeat color from [the Operator contract](https://github.com/leapdao/leap-contracts/blob/master/contracts/PoaOperator.sol#L332). Handle the case, when there is no heartbeat color set (e.g. it is 0) — in this case heartbeat service should not do anything (same as it is now).
- update unit tests

## Deliverables

- updated code
- updated tests

## Gain for the project

easier and less error-prone configuration for the node

## Roles
bounty gardener: @troggy / 30 DAI
bounty worker: @PumpkingWok / share
bounty reviewer: name / share

## Funded by 

Dev Circle

**Comment by PumpkingWok** [comment]
Hi there,
I could try to fix it during the week, if this issue is still free. It seems not so difficult.
Thanks in advance.

**Comment by troggy** [comment]
@PumpkingWok that's great. Good luck

**Comment by PumpkingWok** [comment]
Hi @troggy,
I'm trying to sync a node from scratch, on testnet, but it retrieves an error. 
I did `yarn` and `DEBUG=tendermint,leap-node* node index.js --config=https://testnet-node.leapdao.org` but at some height it retrieves `Trying to spend non-existing output` error. It seems that expect a different hash. Did i do something wrong ? Thanks.

<img width="729" alt="Screen Shot 2020-02-08 at 3 21 04 PM" src="https://user-images.githubusercontent.com/2848253/74086793-a145ca00-4a86-11ea-903d-460a640bdca1.png">

**Comment by troggy** [comment]
@PumpkingWok you don't need testnet for this task. Use local network pls — https://github.com/leapdao/leap-sandbox

**Comment by troggy** [comment]
With local network you are in control of heartbeatColor param on PoaOperator contract, it will mint a token for you etc

**Comment by PumpkingWok** [comment]
Hi @troggy , thanks for the advice.
Just to know, `leap-sandbox` does not work with node 12 too,  i thinks. I had to downgrade node to version 10.

**Comment by troggy** [comment]
yes, not working on node12 so far. I use nvm with node 10 for now.

Don't spend much time on setting up infrastructure. Start with code and unit tests (mock contract calls). It should be a single integration test — I can assist with that, once there is something to test.

**Comment by troggy** [comment]
Setting up local network:
1. Checkout https://github.com/leapdao/leap-sandbox/pull/81 (it supports hearteats out of the box)
2. `yarn`
3. In `build/config` set leap-node path to your local folder
4. `yarn build`
5. `yarn start` — you should have a running network with two nodes, each pushing their own heartbeat NFTs successfully (check `output/node-1.log` for 32769 token transfers. 32769 is a Heartbeat Token color on local network)

**Comment by troggy** [comment]
Once you stuck for more then 20 minutes — ping me pls

**Comment by PumpkingWok** [comment]
Hi @troggy ,
I'm so sorry for the delay, i was very busy unfortunately, i followed your instruction above and i'm testing now. 
Is there a getter method to retrieve `heartbeatColor` variable from `operatorContract` ? i'm looking to find it.thanks

**Comment by troggy** [comment]
> In theory there should be a getter method, created automatically, to retrieve heartbeatColor public variable from operatorContract, right 

`heartbeatColor` is a public field, so the getter is `heartbeatColor()` (e.g. like [this](https://github.com/leapdao/leap-guardian/blob/76a39d12532d22783bf347fa1f4ea7f0fe4c3e17/scripts/setValidator.js#L53))

**Comment by PumpkingWok** [comment]
Hi @troggy,
thanks a lot for the info. I was trying via `operatorContract.methods.heartBeatColor()` and not directly calling `operatorContract.heartbeatColor()`, stupid question. I'm going to open a PR this evening.

**Comment by PumpkingWok** [comment]
Hi @troggy ,
I resolved it, i had to add `heartbeatColor()` getter function into operator abi (`operator.js`), as in `leap-guardian` operator ABI (the repo that you linked to me). Also i had to call it using web3.js `methods` before the method name.

`bridgeState.operatorContract.methods`
    `.heartbeatColor()`
    `.call((error, result) => {`
      `logNode(result);`
    `});`

`leap-guardian` uses `web3.1.0.0-beta.37` version, i think that web3 introduced some changes since `beta38` (ported to ES6, web3-core-method module, ecc)
https://github.com/ethereum/web3.js/releases?after=v1.0.0-beta.46

I'm going to open a WIP PR tomorrow. thanks in advance.

**Comment by troggy** [comment]
👏

Note that we are using async/await in leap-node, so you can actually do something like this:

```js
const heartbeatColor = await bridgeState.operatorContract.methods
.heartbeatColor().call();
```

Regarding leap-guardian and web3. We are not using leap-guardian in leap-node, so don't worry about that.
