### ISSUE TITLE
charge tx fees for non-computation transactions

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#88]
I noticed that inputs and outputs are expected to be equal here: https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/utils.js#L32

how can we charge a tx fee? 

**Option 1 - same as spending condition:**

|  cost table ||
|---|---|
| create utxo | -20,000 gas |
| destroy utxo | +10,000 gas |

1. node calculates gas-cost as in table above.
2. node multiplies gas-cost with gas-price value from tx (needs to be added).
3. node checks that difference between value of LEAP inputs and outputs matches 2.
4. tx only valid if gas-price >= min-gas param from bridge contract.

**Option 2 - flat fee:**

|  cost table ||
|---|---|
| create utxo | -2x LEAP |
| destroy utxo | +x LEAP |

1. node calculates tx fee as in table above.
2. node checks that difference between value of LEAP input and outputs matches 1.
3. tx only valid if ??? >= min-fee param from bridge contract.

**Comment by johannbarbie** [comment]
- what if a fee for a transaction would be storage cost (cost of increasing utxo set) + comp cost? 💥 
- how to charge deposit transactions?

**Comment by sunify** [comment]
1. In which table? :-)
2. What `-2x LEAP` does mean?
3. I don't see any way to charge deposit transaction. You can deposit any token, not having LEAP. Anyway, do we really want to charge deposits? If there is no fee for deposit, it will be easy to deposit and get started with our chain
4. I have a feeling that option 1 is better, but would have a more complex implementation — we would need to implement deterministic gasPrice calculation like for validators set

**Comment by johannbarbie** [comment]
1) updated

2) you have to pay 2 x the amount of leap that you would receive for destroying a UTXO.

3) agree

4) you mean `min-gas` would be a governance parameter, similar validator set?

**Comment by sunify** [comment]
2. Got it (i guess :D)
4. Wrong comparison. More like `epochLength`

**Comment by johannbarbie** [comment]
3. If we have a challenge function in the contract to panelize validators that mine low gas, I think we would not need to manage `mingas` explicitly.

**Comment by sunify** [comment]
So it would be a constant?

**Comment by johannbarbie** [comment]
sh*t, you revealed my faulty opportunistic thinking 🤔

**Comment by johannbarbie** [comment]
@eezcjkr just suggested this 🎉  🌮 :

1. include `minGasPrice` in merkle root of period.
2. submit `minGasPrice` with merkle root and have bridge check that it matches current value in storage.
3. in fraud proof include proof for history `minGasPrice` in same root.

**Comment by sunify** [comment]
So, for color `0` should be `insValue >= outValue + gasFee`, right? Or `insValue == outValue + gasFee` will be better?

**Comment by johannbarbie** [comment]
I'd say: `(ins - outs) / gasPrice = gas` and `gas =  outputs * 20000 - inputs * 10000` as in option 1.
