### ISSUE TITLE
testrun node after refactoring

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#90]
once https://github.com/leapdao/leap-node/issues/85 and https://github.com/leapdao/leap-contracts/issues/65 done, testrun the node to block height 1000 with at least 3 validators.

**Comment by sunify** [comment]
It should be done after each update i suppose

**Comment by eezcjkr** [comment]
# Bounty 29 : Run testnet with tendermint and split contracts

After bounty 27&28 are done, we should verify things are working correctly on a testnet.

## Scope
- testrun the node to block height 1000 with at least 3 validators

## Deliverables
testrun the node to block height 1000 with at least 3 validators

## Gain for the project
QA

----
Bounties: https://github.com/parsec-labs/PIPs/wiki/Bounties

**Comment by troggy** [comment]
delivered and payed out
