### ISSUE TITLE
Stream logs from nodes to online log management system

### ISSUE THREAD

**Issue by sunify** [leapdao/leap-node#96]
e.g. Logz.io (3Gb per day, 3 day retention for free)

## Scope 
- register account on Logz.io. Invite the rest of the team to have access
- set up systemd logs streaming to logz.io from:
   - testnet nodes
   - mainnet nodes
- apart from the message itself, each log entry on Logz.io should contain:
   - date and time
   - environment
   - node instance
- make sure it is possible to search/filter by the above metadata
- make sure it is possible to search by any substring in general

## Deliverables
- shared access to Logz.io web platform
- close to realtime updated logs available on Logz.io for both testnet and mainnet
 
## Gain for the project
- single place to access the logs from all the environments for issue analysis

## Size
Small

## Roles: 
gardener: @troggy / 10% 
worker: @troggy / 80% 
reviewer: _<empty>_ / 10%

**Comment by troggy** [comment]
It is possible to read systemd logs now with

```
ssh -i cyfin.pem ubuntu@testnet-2.leapdao.org journalctl -u leap-node --output cat
```
(add `-f` key to follow the logs' tail)

https://github.com/leapdao/leap-node/issues/16#issuecomment-441445965

Will add some online monitoring (e.g. Logz.io)

**Comment by troggy** [comment]
Viewable in https://app.logz.io/
Filter by `network` and `node`.

Logging set up like that: https://github.com/leapdao/leapdao/wiki/How-to-set-up-logging-to-logz.io
